baseURL = 'http://myriamtousignant.com/'
languageCode = 'fr'
title = 'Myriam Tousignant'
googleAnalytics = 'G-5FWE4D9ED7'
publishDir = 'docs'

[params]
copyrightInfo = '© 2021 Myriam Tousignant Tous Droits Réservés.'
description = 'Artiste, peintre en art contemporain'
keywords = 'Myriam Tousignant, artiste, peintre, peinture, art conteporain, vidéo, animation, Myriam,  Tousignant, expositions, exposition, UQÀM, myriam, myriam tousignant, tousignant'